### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubschool/scaling-guide#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'unsubscribe' button.

**Comment by kilburb** [comment]
Please add me

**Comment by liliahogan** [comment]
hi

**Comment by TriptiT** [comment]
Test

**Comment by hammcastle** [comment]
Anything

**Comment by ryuhsutter** [comment]
test

**Comment by ruskj** [comment]
add me

**Comment by githubteacher** [comment]
🐊

**Comment by ottojsutter** [comment]
Hello :dog:

**Comment by baustin612** [comment]
:dog:

**Comment by bailyd** [comment]
Hi

**Comment by ECRStevens** [comment]
:pizza:

**Comment by KnightRide12** [comment]
Give me access?

**Comment by GuraveH** [comment]
hello, this is Haripriya.

**Comment by Chrispy03** [comment]
Hi :+1:

**Comment by a-a-ron** [comment]
👍

**Comment by potharaju** [comment]
hello!!!

**Comment by zhangm4** [comment]
pls add me

**Comment by murraygsutter** [comment]
TBA

**Comment by zhangm4** [comment]
:pineapple:

**Comment by maricay** [comment]
done...resetting my password :-)

**Comment by velascd** [comment]
Surfer

**Comment by kudelia** [comment]
Hello, finally kudelia can leave a comment!!!!

**Comment by edlav11** [comment]
Please add me

**Comment by allurisushma** [comment]
hello

**Comment by dkwooldridge** [comment]
I'm finally in

**Comment by burnsa2018** [comment]
FINALLY!

**Comment by githubteacher** [comment]
Comment

**Comment by ryuhsutter** [comment]
test2

**Comment by a-a-ron** [comment]
👋  @githubteacher

**Comment by kudelia** [comment]
@burnsa2018 - checking notifications
